### ISSUE TITLE
Highlight Color Reverts Back When Making Same Request

### ISSUE THREAD

**Issue by msakr484** [Regala/burp-scope-monitor#12]
Hello - So I just started using this extension, which sounded really neat, and was seeing a weird behavior with the analyzed endpoints highlighting. Basically, after marking an endpoint as analyzed in the monitor tab (which makes its highlight turn green), if I make the same request in the browser, the monitor reverts the endpoint back to red which gives the false idea that it wasn't analyzed before. This happens regardless of where the endpoint was initially marked as analyzed (monitor or proxy tabs). 

I tried restarting the extension and even reinstalling and keep getting the same result.

**Comment by Regala** [comment]
Hi! Thanks for the feedback. Unfortunately I'm discontinuing the extension. There's a new extension called Progress Tracker which pretty much does the same thing but better, check it out - https://github.com/portswigger/progress-tracker.
Cheers!
